<a href="https://colab.research.google.com/github/anjalidutt/DataAnalytics_Microcredential/blob/assignment_five/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np_city_and_state=np.array([['NYC','LA','MI','Houston'], ['NY','CA','FL','TX']])
np_city = np_city_and_state[0]
np_city_and_state

array([['NYC', 'LA', 'MI', 'Houston'],
       ['NY', 'CA', 'FL', 'TX']], dtype='<U7')

In [ ]:
np_city_and_state.ndim

2

In [ ]:
print(f'Dimension = {np_city.ndim}')
print(f'Shape = {np_city.shape}')
print(f'Size = {np_city.size}')

Dimension = 1
Shape = (4,)
Size = 4


In [ ]:
print(f'Dimension = {np_city_and_state.ndim}')
print(f'Shape = {np_city_and_state.shape}')
print(f'Size = {np_city_and_state.size}')

Dimension = 2
Shape = (2, 4)
Size = 8


In [ ]:
first_trial_cyclist=[10,15,17,26]
second_trial_cyclist=[12,11,21,24]
np_first=np.array(first_trial_cyclist)
np_second = np.array(second_trial_cyclist)
print(np_first)
print(np_second)
total = np_first+np_second
print(total)

[10 15 17 26]
[12 11 21 24]
[22 26 38 50]


In [ ]:
cyclist_trials=np.array([[10,15,17,26],[12,11,21,24]])
first_trial=cyclist_trials[0]
first_trial

array([10, 15, 17, 26])

In [ ]:
second_trial = cyclist_trials[1]
second_trial

array([12, 11, 21, 24])

In [ ]:
print(cyclist_trials)
print(cyclist_trials[1][2])

[[10 15 17 26]
 [12 11 21 24]]
21


In [ ]:
test_scores=np.array([[83,71,57,63],[54,68,81,45]])
passing_scores = test_scores>60
passing_scores
test_scores[passing_scores]

array([83, 71, 63, 68, 81])

In [ ]:
boroughs_in_nyc=np.array(['Manhattan','Queens','Bronx','Brooklyn','Staten Island'])
boroughrs_copy = boroughs_in_nyc.view()#shallow copy
boroughrs_copy[3]="Central Park"
print(boroughs_in_nyc)
print(boroughrs_copy)

['Manhattan' 'Queens' 'Bronx' 'Central Park' 'Staten Island']
['Manhattan' 'Queens' 'Bronx' 'Central Park' 'Staten Island']


In [ ]:
boroughs_in_nyc=np.array(['Manhattan','Queens','Bronx','Brooklyn','Staten Island'])
boroughrs_copy = boroughs_in_nyc.copy()#deep copy
boroughrs_copy[3]="Central Park"
print(boroughs_in_nyc)
print(boroughrs_copy)

['Manhattan' 'Queens' 'Bronx' 'Brooklyn' 'Staten Island']
['Manhattan' 'Queens' 'Bronx' 'Central Park' 'Staten Island']


In [ ]:
np_sqrt=np.sqrt([4,9,16,25])
np_sqrt

array([2., 3., 4., 5.])

In [ ]:
from numpy import pi
pi
np.cos(pi)

-1.0

In [ ]:
np.floor([1,5,2.6,7.8,4,-3,-2.3])

array([ 1.,  5.,  2.,  7.,  4., -3., -3.])

In [ ]:
ar = np.array([1,2,3])
ar = np.exp(ar)
print(ar)

[ 2.71828183  7.3890561  20.08553692]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
c=a+b
print(c)

[11 22 33 44]


In [ ]:
a=np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
b=[1,2,3]
print(f'First array \n{a}')
print(f'Second array \n{b}')
print(f'First array + Second array \n{a+b}')

First array 
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
Second array 
[1, 2, 3]
First array + Second array 
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

In [ ]:
x=np.array([[1,2],[3,4]])
y=np.linalg.inv(x)
print(x)
print(y)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
trace_array=np.array([[1,2],[3,4]])
np.trace(trace_array)

5